# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qdotdongle_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(414, 254)
        self.software_text = QtWidgets.QLineEdit(Dialog)
        self.software_text.setGeometry(QtCore.QRect(200, 80, 191, 22))
        self.software_text.setText("")
        self.software_text.setObjectName("software_text")
        self.EPcable_text = QtWidgets.QLineEdit(Dialog)
        self.EPcable_text.setGeometry(QtCore.QRect(200, 150, 191, 22))
        self.EPcable_text.setText("")
        self.EPcable_text.setObjectName("EPcable_text")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SN_text = QtWidgets.QLineEdit(Dialog)
        self.SN_text.setGeometry(QtCore.QRect(200, 115, 191, 22))
        self.SN_text.setText("")
        self.SN_text.setObjectName("SN_text")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(90, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(250, 200, 93, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.check_button = QtWidgets.QPushButton(Dialog)
        self.check_button.setGeometry(QtCore.QRect(90, 200, 93, 28))
        self.check_button.setObjectName("check_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Dongle HW Version:"))
        self.label.setText(_translate("Dialog", "Dongle SN:"))
        self.title.setText(_translate("Dialog", "QDOT™ Dongle"))
        self.label_2.setText(_translate("Dialog", "Dongle SW Version:"))
        self.confirm_button.setText(_translate("Dialog", "Confirm"))
        self.check_button.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
