# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catheters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(337, 208)
        self.check_button = QtWidgets.QPushButton(Dialog)
        self.check_button.setGeometry(QtCore.QRect(40, 160, 93, 28))
        self.check_button.setObjectName("check_button")
        self.mfg_text_2 = QtWidgets.QLineEdit(Dialog)
        self.mfg_text_2.setGeometry(QtCore.QRect(140, 75, 191, 22))
        self.mfg_text_2.setObjectName("mfg_text_2")
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(200, 160, 93, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mfg_text = QtWidgets.QLineEdit(Dialog)
        self.mfg_text.setGeometry(QtCore.QRect(140, 115, 191, 22))
        self.mfg_text.setObjectName("mfg_text")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(90, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.check_button.setText(_translate("Dialog", "Verify"))
        self.confirm_button.setText(_translate("Dialog", "Confirm"))
        self.label.setText(_translate("Dialog", "MFG Part:"))
        self.title.setText(_translate("Dialog", "Catheters"))
        self.label_2.setText(_translate("Dialog", "Catheter Family:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
