# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(353, 235)
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(140, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.unitV_text = QtWidgets.QLineEdit(Dialog)
        self.unitV_text.setGeometry(QtCore.QRect(140, 120, 191, 22))
        self.unitV_text.setObjectName("unitV_text")
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(190, 180, 93, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.unitSN_text = QtWidgets.QLineEdit(Dialog)
        self.unitSN_text.setGeometry(QtCore.QRect(140, 70, 191, 22))
        self.unitSN_text.setObjectName("unitSN_text")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 65, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.check_button = QtWidgets.QPushButton(Dialog)
        self.check_button.setGeometry(QtCore.QRect(60, 180, 93, 28))
        self.check_button.setObjectName("check_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.unitSN_text, self.unitV_text)
        Dialog.setTabOrder(self.unitV_text, self.check_button)
        Dialog.setTabOrder(self.check_button, self.confirm_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "Printer"))
        self.confirm_button.setText(_translate("Dialog", "Confirm"))
        self.label_2.setText(_translate("Dialog", "Printer SN:"))
        self.label.setText(_translate("Dialog", "Printer Model:"))
        self.check_button.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
