# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smartablate_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(366, 248)
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(80, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.check_button = QtWidgets.QPushButton(Dialog)
        self.check_button.setGeometry(QtCore.QRect(50, 200, 93, 28))
        self.check_button.setObjectName("check_button")
        self.SN_text = QtWidgets.QLineEdit(Dialog)
        self.SN_text.setGeometry(QtCore.QRect(150, 110, 191, 22))
        self.SN_text.setObjectName("SN_text")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.software_text = QtWidgets.QLineEdit(Dialog)
        self.software_text.setGeometry(QtCore.QRect(150, 75, 191, 22))
        self.software_text.setObjectName("software_text")
        self.cables_text = QtWidgets.QLineEdit(Dialog)
        self.cables_text.setGeometry(QtCore.QRect(150, 150, 191, 22))
        self.cables_text.setObjectName("cables_text")
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(210, 200, 93, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.software_text, self.SN_text)
        Dialog.setTabOrder(self.SN_text, self.cables_text)
        Dialog.setTabOrder(self.cables_text, self.check_button)
        Dialog.setTabOrder(self.check_button, self.confirm_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "SmartAblate™"))
        self.check_button.setText(_translate("Dialog", "Verify"))
        self.label.setText(_translate("Dialog", "System SW:"))
        self.confirm_button.setText(_translate("Dialog", "Confirm"))
        self.label_2.setText(_translate("Dialog", "Serial Number:"))
        self.label_3.setText(_translate("Dialog", "Cables:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
